app = "airflow-ai"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"  # ✅ Corrige o build para usar seu Dockerfile

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

